sudo: required

services:
- docker

language: C

before_install:
- docker build -t novation-launchpad-pro-dev .
- docker run -d -v $(pwd):/launchpad-pro novation-launchpad-pro-dev "make"

script:
- make
